---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: productsbackend # Name of the deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: productsbackend
    spec:
      containers:
      - name: productsbackend
        image: rogerchenacr.azurecr.io/productservice:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: productsbackend
  ports:
    - port: 80
      nodePort:  32001
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
---
