apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-frontend-deployment
spec:
  selector:
    matchLabels:
      app: storefrontend
  replicas: 1
  template:
    metadata:
      labels:
        app: storefrontend
    spec:
      containers:
      - name: storefrontend
        image: rogerchenacr.azurecr.io/storeimage:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: ProductEndpoint
          value: http://productsbackend
---
